TestProjectIsDB/Controllers/GradeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestProjectIsDB.Data;
using TestProjectIsDB.Models.Classes;
using TestProjectIsDB.Models.PlayerViewModel;

namespace TestProjectIsDB.Controllers
{
    [Authorize]
    public class GradeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GradeController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public ActionResult GradeList(int pageNumber = 1)
        {
            List<Grade> gradeList = _context.grades.ToList();
            return View(gradeList);
        }
        [HttpGet]
        public ActionResult AddGrade()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddGrade(CreateGradeViewModel viewobj)
        {
            Grade gradeObj = new Grade();
            gradeObj.GradeName = viewobj.GradeName;
            _context.grades.Add(gradeObj);
            _context.SaveChanges();
            RedirectToAction("GradeList");
            return RedirectToAction("GradeList");
        }
        [HttpGet]
        public ActionResult EditGrade(int id)
        {
            Grade gradeObj = _context.grades.SingleOrDefault(g => g.GradeID == id);
            CreateGradeViewModel gradeObj2 = new CreateGradeViewModel();
            if (gradeObj != null)
            {
                // gradeObj = new Grade();
                gradeObj2.GradeName = gradeObj.GradeName;
            }

            return View(gradeObj);
        }
        [HttpPost]
        public ActionResult EditGrade(CreateGradeViewModel viewObj)
        {
            Grade gradeObj = new Grade();
            gradeObj.GradeName = viewObj.GradeName;
            gradeObj.GradeID = viewObj.GradeID;
            _context.Entry(gradeObj).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("GradeList");
        }
        [HttpGet, HttpPost]
        public ActionResult DeleteGrate(int id)
        {
            Grade gradeobj = _context.grades.SingleOrDefault(g => g.GradeID == id);
            if (gradeobj != null)
            {
                _context.grades.Remove(gradeobj);
                _context.SaveChanges();
                return RedirectToAction("GradeList");
            }
            return View(gradeobj);
        }
    }
}

TestProjectIsDB/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using TestProjectIsDB.Data;
using TestProjectIsDB.Models;

namespace TestProjectIsDB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        
            RoleManager<ApplicationRole> _roleManager;
            private readonly ApplicationDbContext _context;

            public RoleController(ApplicationDbContext context, RoleManager<ApplicationRole> roleManager)
            {
                _context = context;
                _roleManager = roleManager;
            }

            [HttpGet]
            public async Task<IActionResult> Index()
            {
                var roles = await _roleManager.Roles.OrderBy(e => e.ControllerName).ThenBy(e => e.ActionName).ToListAsync();
                return View(roles);
            }

            [HttpGet]
            public IActionResult Create()
            {
                List<Type> controllers = Assembly.GetExecutingAssembly().GetTypes().Where(type => typeof(Controller).IsAssignableFrom(type)).ToList();
                ViewData["controllers"] = new SelectList(controllers, "Name", "Name");
                return View(new ApplicationRole());
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create(ApplicationRole applicationRole)
            {
                if (ModelState.IsValid)
                {
                    await _roleManager.CreateAsync(applicationRole);
                    return RedirectToAction("Index");
                }
                List<Type> controllers = Assembly.GetExecutingAssembly().GetTypes().Where(type => typeof(Controller).IsAssignableFrom(type)).ToList();
                ViewData["controllers"] = new SelectList(controllers, "Name", "Name");
                return View(applicationRole);
            }

            [HttpGet]
            public async Task<IActionResult> Edit(string id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var applicationRole = await _roleManager.Roles.FirstAsync(e => e.Id == id);
                if (applicationRole == null)
                {
                    return NotFound();
                }
                return View(applicationRole);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(string id, ApplicationRole applicationRole)
            {
                if (id != applicationRole.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        ApplicationRole role = await _roleManager.FindByIdAsync(applicationRole.Id);
                        role.Name = applicationRole.Name;
                        IdentityResult result = await _roleManager.UpdateAsync(role);
                    }
                    catch (DbUpdateConcurrencyException ex)
                    {
                        foreach (var entry in ex.Entries)
                        {
                            if (entry.Entity is Models.ApplicationRole)
                            {
                                if (!ApplicationRoleExists(applicationRole.Id))
                                {
                                    return NotFound();
                                }
                                else
                                {
                                    var proposedValues = entry.CurrentValues;
                                    var databaseValues = entry.GetDatabaseValues();

                                    foreach (var property in proposedValues.Properties)
                                    {
                                        var proposedValue = proposedValues[property];
                                        var databaseValue = databaseValues[property];
                                    }
                                    entry.OriginalValues.SetValues(databaseValues);
                                }
                            }
                            else
                            {
                                throw new NotSupportedException("Don't know how to handle concurrency conflicts for " + entry.Metadata.Name);
                            }
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(applicationRole);
            }

            public JsonResult GetActions(string controllerName)
            {
                List<string> actions = Assembly.GetExecutingAssembly().GetTypes().Where(type => typeof(Controller).IsAssignableFrom(type) && type.Name == controllerName)
                    .SelectMany(type => type.GetMethods(BindingFlags.Instance | BindingFlags.DeclaredOnly | BindingFlags.Public))
                    .Where(m => m.GetCustomAttributes(typeof(Microsoft.AspNetCore.Mvc.HttpGetAttribute), true).Any())
                    .GroupBy(e => e.Name)
                    .Select(x => x.FirstOrDefault().Name).ToList();
                return Json(actions);
            }

            private bool ApplicationRoleExists(string id)
            {
                return _context.Roles.Any(e => e.Id == id);
            }
        
    }
}

TestProjectIsDB/Views/Shared/_DetailsRecord.cshtml
@model TestProjectIsDB.Models.PlayerViewModel.PlayerListViewModel
@{
    ViewBag.Title = "Details";
    var photoPath = "/Images/" + (Model.ImageUrl ?? "no.png");
}


<h2>Player Details Information</h2>
<div class="container">
    <dl>
        <dt>
            <label>Name</label>
        </dt>
        <dd>

            @Html.DisplayFor(p => p.Name);
        </dd>
        <dt>
            <label>Date Of Birth</label>
        </dt>
        <dd>

            @Html.DisplayNameFor(p => p.DoB)

        </dd>
        <dt>
            @Html.DisplayNameFor(p => p.Team)
        </dt>
        <dd>

            @Html.DisplayFor(p => p.Team);
        </dd>
        <dt>
            @Html.DisplayNameFor(p => p.Email)
        </dt>
        <dd>

            @Html.DisplayFor(p => p.Email);
        </dd>
        <dt>
            @Html.DisplayNameFor(p => p.Phone)
        </dt>
        <dd>

            @Html.DisplayFor(p => p.Phone);
        </dd>
        <dt>
            @Html.DisplayNameFor(p => p.Salary)
        </dt>
        <dd>

            @Html.DisplayFor(p => p.Salary);
        </dd>
        @*<dt>
                <label>Grade</label>
            </dt>
            <dd>

                @Html.DisplayFor(p => p.GradeName);
            </dd>*@
        <dt>
            <label>Image</label>
        </dt>
        <dd>
            <img src="@photoPath" width="75" height="80" />
        </dd>
    </dl>
    @Html.ActionLink("Back to List", "Index");
</div>

TestProjectIsDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestProjectIsDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:#18ffff">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestProjectIsDB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Order
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">City</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Product
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Item</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Index">Supplier</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Grade" asp-action="GradeList">Grade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Player</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AjaxCrud" asp-action="Index">AjaxCrud</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">SPA</a>
                        </li>
                        @{ if (User.Identity.IsAuthenticated)
                            {
                                List<TestProjectIsDB.ViewModels.Menu> menus = TestProjectIsDB.Data.RolesForMenu.GetMenus(User.Identity.Name);
                                foreach (TestProjectIsDB.ViewModels.Menu menu in menus)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="@menu.ControllerName" asp-action="@menu.ActionName">@menu.RoleName</a>
                                    </li>
                                }
                                if (User.IsInRole("Admin"))
                                {

                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="UserRole" asp-action="Index">User Role</a>
                                    </li>
                                }
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestProjectIsDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TestProjectIsDB/Views/Shared/_PlayerDetailsPartial.cshtml
@model TestProjectIsDB.Models.PlayerViewModel.PlayerListViewModel
@{
    var photoPath = "/Images/" + (Model.ImageUrl ?? "no.png");
}
<div>
    <h4>Player Details</h4>
    <br />
    <table class="table table-bordered">
        <tr>
            <th>Player ID</th>
            <td>@Html.DisplayFor(p => p.PlayerID)</td>
        </tr>
        <tr>
            <th>Player Name</th>
            <td>@Html.DisplayFor(p => p.Name)</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>@Html.DisplayFor(p => p.Email)</td>
        </tr>
        <tr>
            <th>Date of Birth</th>
            <td>@Html.DisplayFor(p => p.DoB)</td>
        </tr>
        <tr>
            <th>Phone</th>
            <td>@Html.DisplayFor(p => p.Phone)</td>
        </tr>
        <tr>
            <th>Team</th>
            <td>@Html.DisplayFor(p => p.Team)</td>
        </tr>
        <tr>
            <th>Salary</th>
            <td>@Html.DisplayFor(p => p.Salary)</td>
        </tr>
        <tr>
            <th>Image</th>
            <th><img src="@photoPath" width="75" height="80" /></th>
        </tr>

    </table>
</div>