TestProjectIsDB/Models/Classes/Item.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TestProjectIsDB.Models.Classes
{
    public class Item
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ID { get; set; }

        [Required, Display(Name = "Product Name")]
        public string Name { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        //[Column(TypeName = "image")]
        public string Image { get; set; }

        //[Required, Today, DataType(DataType.Date), Column(TypeName = "date"), Display(Name = "Entry Date")]
        public DateTime EntryDate { get; set; }

        [Required]
        public long Quantity { get; set; }

        [ForeignKey("Category")]
        public long CategoryID { get; set; }

        //[ForeignKey("CategoryID")] -- You can reference foreign key here
        public virtual Category Category { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
    }
}

TestProjectIsDB/Controllers/ItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestProjectIsDB.Attributes;
using TestProjectIsDB.Data;
using TestProjectIsDB.Models;

namespace TestProjectIsDB.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        
            private readonly ApplicationDbContext _context;

            public ItemController(ApplicationDbContext context)
            {
                _context = context;
            }

            [HttpGet]
            [AllowAnonymous]
            public async Task<IActionResult> Index()
            {
                ViewData["Create"] = RolesForMenu.GetMenu(User.Identity.Name, "Item", "Create");
                ViewData["Edit"] = RolesForMenu.GetMenu(User.Identity.Name, "Item", "Edit");
                ViewData["Delete"] = RolesForMenu.GetMenu(User.Identity.Name, "Item", "Delete");

                var applicationDbContext = _context.OrderItems.Include(o => o.Order).Include(o => o.Product);
                return View(await applicationDbContext.ToListAsync());
            }

            [HttpGet]
            public async Task<IActionResult> Details(long? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var orderItem = await _context.OrderItems
                    .Include(o => o.Order)
                    .Include(o => o.Product)
                    .FirstOrDefaultAsync(m => m.ID == id);
                if (orderItem == null)
                {
                    return NotFound();
                }

                return View(orderItem);
            }

            [HttpGet]
            [CustomAuthorize("Item", "Create")]
            public IActionResult Create()
            {
                ViewData["OrderId"] = new SelectList(_context.Orders, "ID", "OrderNumber");
                ViewData["ProductId"] = new SelectList(_context.Products, "ID", "ProductName");
                return View();
            }

            [HttpPost]
            [CustomAuthorize("Item", "Create")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create([Bind("ID,OrderId,ProductId,UnitPrice,Quantity")] OrderItem orderItem)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(orderItem);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["OrderId"] = new SelectList(_context.Orders, "ID", "OrderNumber", orderItem.OrderId);
                ViewData["ProductId"] = new SelectList(_context.Products, "ID", "ProductName", orderItem.ProductId);
                return View(orderItem);
            }

            [HttpGet]
            [CustomAuthorize("Item", "Edit")]
            public async Task<IActionResult> Edit(long? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var orderItem = await _context.OrderItems.FindAsync(id);
                if (orderItem == null)
                {
                    return NotFound();
                }
                ViewData["OrderId"] = new SelectList(_context.Orders, "ID", "OrderNumber", orderItem.OrderId);
                ViewData["ProductId"] = new SelectList(_context.Products, "ID", "ProductName", orderItem.ProductId);
                return View(orderItem);
            }

            [HttpPost]
            [CustomAuthorize("Item", "Edit")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(long id, [Bind("ID,OrderId,ProductId,UnitPrice,Quantity")] OrderItem orderItem)
            {
                if (id != orderItem.ID)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(orderItem);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!OrderItemExists(orderItem.ID))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ViewData["OrderId"] = new SelectList(_context.Orders, "ID", "OrderNumber", orderItem.OrderId);
                ViewData["ProductId"] = new SelectList(_context.Products, "ID", "ProductName", orderItem.ProductId);
                return View(orderItem);
            }

            [HttpGet]
            [CustomAuthorize("Item", "Delete")]
            public async Task<IActionResult> Delete(long? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var orderItem = await _context.OrderItems
                    .Include(o => o.Order)
                    .Include(o => o.Product)
                    .FirstOrDefaultAsync(m => m.ID == id);
                if (orderItem == null)
                {
                    return NotFound();
                }

                return View(orderItem);
            }

            [HttpPost, ActionName("Delete")]
            [CustomAuthorize("Item", "Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(long id)
            {
                var orderItem = await _context.OrderItems.FindAsync(id);
                _context.OrderItems.Remove(orderItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            private bool OrderItemExists(long id)
            {
                return _context.OrderItems.Any(e => e.ID == id);
            }
        
    }
}

TestProjectIsDB/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TestProjectIsDB.Data;
using TestProjectIsDB.Models.Classes;

namespace TestProjectIsDB.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IWebHostEnvironment _webHostEnvironment { get; }

        public ItemsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }


        public ActionResult Create(long? id)
        {
            if (id == null)
            {
                ViewBag.CategoryID = new SelectList(_context.Categories, "ID", "Name");
            }
            else
            {
                ViewBag.CategoryID = new SelectList(_context.Categories, "ID", "Name", id);
            }
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("ID,Name,Description,EntryDate,Quantity,CategoryID")] Item item, IFormFile file)
        {
            //string path = "";
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    // To save a image to a folder
                    string picture = System.IO.Path.GetFileName(file.FileName);
                    //path = ProcessUploadFile();
                    //file.SaveAs(path);

                    // To store as byte[] in a Table of Database
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.CopyTo(ms);
                        item.Image = ms.GetBuffer().ToString();
                    }
                    _context.Items.Add(item);
                    await _context.SaveChangesAsync();
                    TempData["id"] = item.CategoryID;
                    return RedirectToAction("Index", "Categories");
                }
                else
                {
                    ViewBag.CategoryID = new SelectList(_context.Categories, "ID", "Name", item.CategoryID);
                    return PartialView(item);
                }
            }
            ViewBag.CategoryID = new SelectList(_context.Categories, "ID", "Name", item.CategoryID);
            return PartialView(item);
        }

        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                //return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(_context.Categories, "ID", "Name", item.CategoryID);
            return PartialView(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("ID,Name,Description,Image,EntryDate,Quantity,CategoryID")] Item item, IFormFile file)
        {
            string path = "";
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    // To save a image to a folder
                    //string picture = System.IO.Path.GetFileName(file.FileName);
                    path = ProcessUploadFile();
                    //file.SaveAs(path);

                    // To store as byte[] in a Table of Database
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.CopyTo(ms);
                        item.Image = ms.GetBuffer().ToString();
                    }
                }
                _context.Entry(item).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                TempData["id"] = item.CategoryID;
                return RedirectToAction("Index", "Categories");
            }
            ViewBag.CategoryID = new SelectList(_context.Categories, "ID", "Name", item.CategoryID);
            return PartialView(item);
        }

        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                //return HttpNotFound();
            }
            return PartialView(item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            Item item = await _context.Items.FindAsync(id);
            _context.Items.Remove(item);
            await _context.SaveChangesAsync();
            TempData["id"] = item.CategoryID;
            return RedirectToAction("Index", "Categories");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }


        private string ProcessUploadFile()
        {
            string uniqueFileName = null;
            var files = HttpContext.Request.Form.Files;
            foreach (var image in files)
            {
                if (image != null && image.Length > 0)
                {
                    var file = image;
                    var uploadFile = Path.Combine(_webHostEnvironment.WebRootPath, "Images");
                    if (file.Length > 0)
                    {
                        var fileName = file.FileName;
                        using (var fileStream = new FileStream(Path.Combine(uploadFile, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                            uniqueFileName = fileName;
                        }
                    }

                }
            }

            return uniqueFileName;
        }

    }
}

TestProjectIsDB/Views/Items/Create.cshtml
@model TestProjectIsDB.Models.Classes.Item

<form enctype="multipart/form-data" asp-controller="Items" asp-action="Create" method="post" class="mt-3">
    <div class="modal-header">
        <h5 class="modal-title" id="itemModalLabel">Add new product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
        <div class="form-group">
            <label>Name:</label>
            <input asp-for="Name" class="form-control" placeholder="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label>Description:</label>
            <input asp-for="Description" class="form-control" placeholder="Name" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label>Image</label>
            <br />
            <img id="itemImage" src="~/Images/transparent_phone.jpg" height="80" width="75" />
            <input id="file" name="file" type="file" onchange="loadImage(event)" />
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label>Entry Date:</label>
            <input asp-for="EntryDate" class="form-control" placeholder="Name" />
            <span asp-validation-for="EntryDate" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label>Quantity:</label>
            <input asp-for="Quantity" class="form-control" placeholder="Name" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "col-form-label" })
            @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary" value="Save" />
    </div>

</form>

TestProjectIsDB/Views/Items/Delete.cshtml
@model TestProjectIsDB.Models.Classes.Item

@{ ViewBag.Title = "Delete"; }

<div class="modal-header">
    <h5 class="modal-title" id="deleteItemModalLabel">Delete product</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="card">
        <img src="@Model.Image" />

        <div class="card-body">
            <h5 class="card-title">@Html.DisplayFor(model => model.Name)</h5>
            <p class="card-text">
                @Html.DisplayNameFor(model => model.Category.Name):&nbsp;@Html.DisplayFor(model => model.Category.Name)
                <br />
                @Html.DisplayNameFor(model => model.Description):&nbsp;@Html.DisplayFor(model => model.Description)
                <br />
                @Html.DisplayNameFor(model => model.EntryDate):&nbsp;@Html.DisplayFor(model => model.EntryDate)
                <br />
                @Html.DisplayNameFor(model => model.Quantity):&nbsp;@Html.DisplayFor(model => model.Quantity)
            </p>
        </div>
    </div>
</div>
<div class="modal-footer">

    <form enctype="multipart/form-data" asp-controller="Items" asp-action="Delete" method="post" class="mt-3">
        @Html.AntiForgeryToken()
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary" value="Delete" />

    </form>


</div>

TestProjectIsDB/Views/Items/Edit.cshtml
@model TestProjectIsDB.Models.Classes.Item


<form enctype="multipart/form-data" asp-controller="Items" asp-action="Edit" method="post" class="mt-3">
    <div class="modal-header">
        <h5 class="modal-title" id="editItemModalLabel">Edit product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label>Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group">

            <label>Description</label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label>Image</label>
            <br />
            <img src="@Model.Image" height="65" width="60" />

            <input id="file" name="file" type="file" onchange="editImage(event)" />
            <span asp-validation-for="Image"></span>
            <input type="hidden" asp-for="Image" />
        </div>

        <div class="form-group">

            <label>Entry Date</label>
            <input asp-for="EntryDate" class="form-control" />
            <span asp-validation-for="EntryDate" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label>Quantity</label>
            <input asp-for="Quantity" class="form-control" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>

        <div class="form-group">

            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "col-form-label" })
            @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary" value="Save" />
    </div>

</form>